language: generic
sudo: required
services: 
  - docker
  
before_install:
  - docker build -t jobothehobo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jobothehobo/docker-react npm run test -- --coverage